services:
  backend:
    build: ./backend
    container_name: backend
    command: ["node", "server.js"]
    ports:
      - "9000:9000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker:
    build: ./backend  
    container_name: worker
    command: ["node", "triageWorker.js"]
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
